// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bikpiaqgryrwnzheimgf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJpa3BpYXFncnlyd256aGVpbWdmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwOTQ0NzgsImV4cCI6MjA2ODY3MDQ3OH0.RHQyxaeFmVP0beTqXuIdVTnLx6H98AdPl93UJ1VkH60";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});